# Generated by Django 6.1.1 on 2026-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('service_interest', models.CharField(default='General Inquiry', max_length=150)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short project title, e.g. EchoWithin', max_length=200)),
                ('full_title', models.CharField(blank=True, help_text='Editorial title, e.g. EchoWithin - Private Encrypted Notes & Social Bonds Platform', max_length=250)),
                ('slug', models.SlugField(help_text='Unique URL identifier (e.g. echowithin-encrypted-platform)', max_length=200, unique=True)),
                ('client', models.CharField(help_text='Client name, e.g. EchoWithin or VIN-KJ Auto Services', max_length=150)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('E-Commerce', 'E-Commerce'), ('Cybersecurity', 'Cybersecurity'), ('Graphic Design', 'Graphic Design'), ('Video Editing', 'Video Editing')], default='Web Development', max_length=100)),
                ('year', models.CharField(default='2026', max_length=10)),
                ('live_url', models.URLField(blank=True, help_text='Direct link to client live website (e.g. https://echowithin.xyz or https://vinkj.com)', null=True)),
                ('image_url', models.CharField(default='img/echowithin-platform.webp', help_text='Static image path (e.g. img/echowithin-platform.webp) or full external URL', max_length=300)),
                ('summary', models.TextField(help_text='Short teaser description shown on cards')),
                ('challenge', models.TextField(blank=True, help_text='The client challenge')),
                ('solution', models.TextField(blank=True, help_text='The technical solution delivered')),
                ('deliverables_summary', models.TextField(blank=True, help_text='Summary of completed deliverables')),
                ('metric_1_val', models.CharField(blank=True, default='0', max_length=50)),
                ('metric_1_label', models.CharField(blank=True, default='Unencrypted data leaks', max_length=100)),
                ('metric_2_val', models.CharField(blank=True, default='1.0s', max_length=50)),
                ('metric_2_label', models.CharField(blank=True, default='Core web speed index', max_length=100)),
                ('metric_3_val', models.CharField(blank=True, default='100%', max_length=50)),
                ('metric_3_label', models.CharField(blank=True, default='Mobile responsiveness', max_length=100)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage under Featured Work')),
                ('is_published', models.BooleanField(default=True, help_text='Show publicly on the website')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Project',
                'verbose_name_plural': 'Work Projects',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
