# Generated by Django 6.1.1 on 2026-10-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='metric_1_label',
        ),
        migrations.RemoveField(
            model_name='work',
            name='metric_1_val',
        ),
        migrations.RemoveField(
            model_name='work',
            name='metric_2_label',
        ),
        migrations.RemoveField(
            model_name='work',
            name='metric_2_val',
        ),
        migrations.RemoveField(
            model_name='work',
            name='metric_3_label',
        ),
        migrations.RemoveField(
            model_name='work',
            name='metric_3_val',
        ),
    ]
