# Generated by Django 6.1.1 on 2026-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_work_metric_1_label_remove_work_metric_1_val_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=250)),
                ('slug', models.SlugField(help_text='URL slug (e.g. building-echowithin-platform)', max_length=250, unique=True)),
                ('category', models.CharField(choices=[('Engineering & Architecture', 'Engineering & Architecture'), ('Web Development', 'Web Development'), ('Cybersecurity', 'Cybersecurity'), ('Design Systems', 'Design Systems'), ('Studio Notes', 'Studio Notes')], default='Engineering & Architecture', max_length=100)),
                ('author', models.CharField(default='Vincent Odhiambo & Timothy Owino', max_length=150)),
                ('reading_time', models.CharField(default='4 min read', max_length=50)),
                ('summary', models.TextField(help_text='Introductory summary / lead excerpt shown on card feeds')),
                ('content', models.TextField(help_text='Complete article body. Supports clean multi-line paragraphs and section headers (### Header).')),
                ('is_published', models.BooleanField(default=True, help_text='Display publicly on the website')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
